export enum productsActions {
  SET_PRODUCTS = 'SET_PRODUCTS',
  DELETE_PRODUCT = 'DELETE_PRODUCT',
  UPDATE_PRODUCT = 'UPDATE_PRODUCT',
  CREATE_PRODUCT = 'CREATE_PRODUCT',
  ADD_PRODUCT = 'ADD_PRODUCT',
}
